In [1]:
import numpy as np

In [2]:
#первое задание

numbers = np.array([8, 7, 6, 5, 4, 3, 2, 1, 0])
print(numbers)

[8 7 6 5 4 3 2 1 0]


In [3]:
#второе задание

n = numbers.reshape(3,3)
print('Матрица:')
print(n)

diag1 = np.asarray(n)
diag2 = np.fliplr(diag1)
print('Сумма диагоналей матрицы:',np.trace(diag1)+np.trace(diag2))

Матрица:
[[8 7 6]
 [5 4 3]
 [2 1 0]]
Сумма диагоналей матрицы: 24


In [5]:
#задание третье 

# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

a = np.array([[4,2,1],[1,3,0],[5,4,0]])
b = np.array([4,12,-3])

from numpy import linalg

print(linalg.solve(a, b))
np.allclose(np.dot(a, linalg.solve(a, b)), b) #проверка

[-5.18181818  5.72727273 13.27272727]


True

In [54]:
#задание четвертое

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
maxvalue = 0
usernumber = 0

for user in users_stats:
    usernumber += 1
    aLength = np.linalg.norm(user)
    bLength = np.linalg.norm(next_user_stats)    
    cos = (np.dot(user,next_user_stats)/(aLength*bLength))
    if cos > maxvalue:
        maxvalue = cos
        usern = usernumber
print('Наиболее похожий пользователь находится под номером', usern)
print('Косинусное сходство между этим пользователем и новым посетителем', maxvalue)

Наиболее похожий пользователь находится под номером 8
Косинусное сходство между этим пользователем и новым посетителем 0.9486832980505138
